# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbea48ea39ccc58a5837e041a2ba71a9852b66c42c50a25ccf63c01c99a0e39ba0571ef032f11e8c5fc5090ce71d0c80dadd86be2b3d38a22f4aed0e0e300a11

test:
  secret_key_base: 69485c1aa90ea511cbfa4eb0b1d3b173ae54f5f939d9485e774832597b7d4c119b18c214a13f3d1833a7e20fb98d2c9172b012c55b14ee04125e74ba0f317b03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
